"""Split QR to fields

Revision ID: 73bb35253d52
Revises: 9e6f23bb36f2
Create Date: 2026-07-28 00:15:31.067527

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "73bb35253d52"
down_revision: Union[str, Sequence[str], None] = "9e6f23bb36f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("receipts_orm", sa.Column("t", sa.TIMESTAMP(timezone=False), nullable=True))
    op.add_column("receipts_orm", sa.Column("s", sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column("receipts_orm", sa.Column("fn", sa.String(length=20), nullable=True))
    op.add_column("receipts_orm", sa.Column("i", sa.String(length=20), nullable=True))
    op.add_column("receipts_orm", sa.Column("fp", sa.String(length=20), nullable=True))
    op.add_column("receipts_orm", sa.Column("n", sa.SmallInteger(), nullable=True))

    # Split QR to t, s, fn, i, fp, and n
    op.execute("""
        UPDATE receipts_orm
        SET
            t = CASE
                    WHEN qr_code ~ 't=([^&]+)' THEN
                        (substring(qr_code, 't=([^&]+)'))::timestamp
                    ELSE NULL
                END,
            s = CASE
                    WHEN qr_code ~ '&s=([^&]+)' THEN
                        (substring(qr_code, '&s=([^&]+)'))::numeric(12,2)
                    ELSE NULL
                END,
            fn = CASE
                    WHEN qr_code ~ '&fn=([^&]+)' THEN
                        substring(qr_code, '&fn=([^&]+)')
                    ELSE NULL
                END,
            i = CASE
                    WHEN qr_code ~ '&i=([^&]+)' THEN
                        substring(qr_code, '&i=([^&]+)')
                    ELSE NULL
                END,
            fp = CASE
                    WHEN qr_code ~ '&fp=([^&]+)' THEN
                        substring(qr_code, '&fp=([^&]+)')
                    ELSE NULL
                END,
           n = CASE
                    WHEN qr_code ~ '&n=([^&]+)' THEN
                        (substring(qr_code, '&n=([^&]+)'))::smallint
                    ELSE NULL
                END
        WHERE qr_code IS NOT NULL AND qr_code != '';
    """)

    op.drop_index(op.f("ix_receipts_id"), table_name="receipts_orm")
    op.drop_index(op.f("ix_receipts_qr_code"), table_name="receipts_orm")
    op.create_index(op.f("ix_receipts_orm_id"), "receipts_orm", ["id"], unique=False)
    op.create_index(op.f("ix_receipts_orm_qr_code"), "receipts_orm", ["qr_code"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_receipts_orm_qr_code"), table_name="receipts_orm")
    op.drop_index(op.f("ix_receipts_orm_id"), table_name="receipts_orm")
    op.create_index(op.f("ix_receipts_qr_code"), "receipts_orm", ["qr_code"], unique=True)
    op.create_index(op.f("ix_receipts_id"), "receipts_orm", ["id"], unique=False)
    op.drop_column("receipts_orm", "n")
    op.drop_column("receipts_orm", "fp")
    op.drop_column("receipts_orm", "i")
    op.drop_column("receipts_orm", "fn")
    op.drop_column("receipts_orm", "s")
    op.drop_column("receipts_orm", "t")
    # ### end Alembic commands ###
