"""
Fiscal fields as base

Revision ID: d6bb0ed0d788
Revises: 73bb35253d52
Create Date: 2026-08-08 01:50:22.629731

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d6bb0ed0d788"
down_revision: Union[str, Sequence[str], None] = "73bb35253d52"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "receipts_orm",
        "t",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_comment="Receipt timestamp",
    )
    op.alter_column(
        "receipts_orm",
        "s",
        existing_type=sa.NUMERIC(precision=15, scale=2),
        nullable=False,
        existing_comment="Total amount",
    )
    op.alter_column(
        "receipts_orm",
        "fn",
        existing_type=sa.BIGINT(),
        nullable=False,
        existing_comment="Fiscal drive number (ФН)",
    )
    op.alter_column(
        "receipts_orm",
        "i",
        existing_type=sa.BIGINT(),
        nullable=False,
        comment="Fiscal document number (ФД)",
        existing_comment="Fiscal document number (номер чека)",
    )
    op.alter_column(
        "receipts_orm",
        "fp",
        existing_type=sa.BIGINT(),
        nullable=False,
        existing_comment="Fiscal sign (ФП)",
    )
    op.alter_column(
        "receipts_orm",
        "n",
        existing_type=sa.SMALLINT(),
        nullable=False,
        existing_comment="Operation type",
    )
    op.drop_index(op.f("ix_receipts_orm_qr_code"), table_name="receipts_orm")
    op.drop_column("receipts_orm", "qr_code")
    op.drop_column("receipts_orm", "created_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "receipts_orm",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
            comment="Timestamp when the receipt was created",
        ),
    )
    op.add_column(
        "receipts_orm",
        sa.Column(
            "qr_code",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
            comment="QR code content for the receipt",
        ),
    )
    op.create_index(
        op.f("ix_receipts_orm_qr_code"), "receipts_orm", ["qr_code"], unique=True
    )
    op.alter_column(
        "receipts_orm",
        "n",
        existing_type=sa.SMALLINT(),
        nullable=True,
        existing_comment="Operation type",
    )
    op.alter_column(
        "receipts_orm",
        "fp",
        existing_type=sa.BIGINT(),
        nullable=True,
        existing_comment="Fiscal sign (ФП)",
    )
    op.alter_column(
        "receipts_orm",
        "i",
        existing_type=sa.BIGINT(),
        nullable=True,
        comment="Fiscal document number (номер чека)",
        existing_comment="Fiscal document number (ФД)",
    )
    op.alter_column(
        "receipts_orm",
        "fn",
        existing_type=sa.BIGINT(),
        nullable=True,
        existing_comment="Fiscal drive number (ФН)",
    )
    op.alter_column(
        "receipts_orm",
        "s",
        existing_type=sa.NUMERIC(precision=15, scale=2),
        nullable=True,
        existing_comment="Total amount",
    )
    op.alter_column(
        "receipts_orm",
        "t",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_comment="Receipt timestamp",
    )
    # ### end Alembic commands ###
