"""
Constraint on full fiscal data

Revision ID: ef1a4a44636e
Revises: 3b73eac12d24
Create Date: 2026-08-08 13:40:04.681077

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ef1a4a44636e"
down_revision: Union[str, Sequence[str], None] = "3b73eac12d24"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_receipts_orm_fn"), "receipts_orm", type_="unique")
    op.create_unique_constraint(
        op.f("uq_receipts_orm_t"), "receipts_orm", ["t", "s", "fn", "i", "fp", "n"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_receipts_orm_t"), "receipts_orm", type_="unique")
    op.create_unique_constraint(
        op.f("uq_receipts_orm_fn"),
        "receipts_orm",
        ["fn", "i", "fp"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
