"""
Rename CRPT data

Revision ID: e31d5e4a0976
Revises: d6bb0ed0d788
Create Date: 2026-08-08 11:28:26.930339

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e31d5e4a0976"
down_revision: Union[str, Sequence[str], None] = "d6bb0ed0d788"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "receipts_orm",
        "receipt_data",
        new_column_name="crpt_data",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_comment="Full receipt data in JSON format from CRPT API",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "receipts_orm",
        "crpt_data",
        new_column_name="receipt_data",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_comment="Full receipt data in JSON format",
    )
    # ### end Alembic commands ###
