"""
Make UTC+0 timestamps

Revision ID: 08d523a284ef
Revises: ef1a4a44636e
Create Date: 2026-08-08 16:37:31.092712

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = "08d523a284ef"
down_revision: Union[str, Sequence[str], None] = "ef1a4a44636e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()

    update_query = text("""
        UPDATE receipts_orm 
        SET t = to_timestamp(
            (crpt_data->'fiscalData'->'codeData'->>'fiscalDate')::bigint / 1000)
            AT TIME ZONE 'UTC'
        WHERE
            crpt_data->'fiscalData'->'codeData'->>'fiscalDate'
            IS NOT NULL
    """)

    connection.execute(update_query)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
