"""
Fiscal constraints

Revision ID: 3b73eac12d24
Revises: e31d5e4a0976
Create Date: 2026-08-08 11:57:04.392671

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3b73eac12d24"
down_revision: Union[str, Sequence[str], None] = "e31d5e4a0976"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "receipts_orm",
        "crpt_data",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="Full receipt data in JSON format from CRPT API",
        existing_comment="Full receipt data in JSON format",
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_receipts_orm_id"), table_name="receipts_orm")
    op.create_index(op.f("ix_receipts_orm_id"), "receipts_orm", ["id"], unique=True)
    op.create_unique_constraint(
        op.f("uq_receipts_orm_fn"), "receipts_orm", ["fn", "i", "fp"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_receipts_orm_fn"), "receipts_orm", type_="unique")
    op.drop_index(op.f("ix_receipts_orm_id"), table_name="receipts_orm")
    op.create_index(op.f("ix_receipts_orm_id"), "receipts_orm", ["id"], unique=False)
    op.alter_column(
        "receipts_orm",
        "crpt_data",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="Full receipt data in JSON format",
        existing_comment="Full receipt data in JSON format from CRPT API",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
