"""Index by crpt json qr code

Revision ID: 15834acb2e9b
Revises: 508593a0dd80
Create Date: 2026-08-26 22:40:24.623772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15834acb2e9b'
down_revision: Union[str, Sequence[str], None] = '508593a0dd80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_crpt_dump_code', 'crpt_orm', [sa.literal_column("(dump->>'code')")], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_crpt_dump_code', table_name='crpt_orm')
    # ### end Alembic commands ###
