"""Drop database

Revision ID: 9e4ba22331bd
Revises: 1e9f6510381b
Create Date: 2026-08-22 23:40:55.628332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e4ba22331bd'
down_revision: Union[str, Sequence[str], None] = '1e9f6510381b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_orm_id'), table_name='items_orm')
    op.drop_index(op.f('ix_items_orm_receipt_id'), table_name='items_orm')

    op.drop_index(op.f('ix_employees_orm_id'), table_name='employees_orm')
    op.drop_index(op.f('ix_employees_orm_shop_id'), table_name='employees_orm')
    op.drop_table('employees_orm')

    op.drop_index(op.f('ix_shops_orm_id'), table_name='shops_orm')
    op.drop_index(op.f('ix_shops_orm_retailer_id'), table_name='shops_orm')
    op.drop_index(op.f('ix_unique_online_shop_per_retailer'), table_name='shops_orm', postgresql_where='(address IS NULL)')
    op.drop_table('shops_orm')

    op.drop_index(op.f('ix_receipts_orm_crpt_id'), table_name='receipts_orm')
    op.drop_index(op.f('ix_receipts_orm_id'), table_name='receipts_orm')
    op.drop_table('receipts_orm')

    op.drop_index(op.f('ix_crpt_orm_id'), table_name='crpt_orm')
    op.drop_table('crpt_orm')

    op.drop_index(op.f('ix_retailers_orm_id'), table_name='retailers_orm')
    op.drop_table('retailers_orm')

    op.drop_index(op.f('ix_nds_orm_id'), table_name='nds_orm')
    op.drop_table('nds_orm')

    op.drop_index(op.f('ix_measures_orm_id'), table_name='measures_orm')
    op.drop_table('measures_orm')

    op.drop_index(op.f('ix_payments_orm_id'), table_name='payments_orm')
    op.drop_table('payments_orm')

    op.drop_index(op.f('ix_products_orm_id'), table_name='products_orm')
    op.drop_table('products_orm')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees_orm',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False, comment='Unique identifier for the employee'),
    sa.Column('shop_id', sa.UUID(), autoincrement=False, nullable=False, comment='Foreign key to shops table'),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Employee name'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops_orm.id'], name=op.f('fk_employees_orm_shop_id_shops_orm'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees_orm')),
    sa.UniqueConstraint('shop_id', 'name', name=op.f('uq_employees_orm_shop_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_employees_orm_shop_id'), 'employees_orm', ['shop_id'], unique=False)
    op.create_index(op.f('ix_employees_orm_id'), 'employees_orm', ['id'], unique=True)
    op.create_table('products_orm',
    sa.Column('id', sa.SMALLINT(), server_default=sa.text("nextval('products_orm_id_seq'::regclass)"), autoincrement=True, nullable=False, comment='Unique identifier of the VAT (НДС)'),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False, comment='VAT (НДС) description'),
    sa.Column('pf_format', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Short string code for print format of payment type'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products_orm'))
    )
    op.create_index(op.f('ix_products_orm_id'), 'products_orm', ['id'], unique=True)
    op.create_table('retailers_orm',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False, comment='Unique identifier for the retailer'),
    sa.Column('inn', sa.VARCHAR(length=12), autoincrement=False, nullable=False, comment='TIN (ИНН) of a company or a single persona'),
    sa.Column('is_individual', sa.BOOLEAN(), sa.Computed('(length((inn)::text) = 12)', persisted=True), autoincrement=False, nullable=False, comment='Flag is the retailer is individual one, company otherwise'),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Name of a company or a persona'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retailers_orm'))
    )
    op.create_index(op.f('ix_retailers_orm_id'), 'retailers_orm', ['id'], unique=True)
    op.create_table('items_orm',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False, comment='Unique identifier for the item'),
    sa.Column('receipt_id', sa.UUID(), autoincrement=False, nullable=False, comment='Relations to receipt with this item'),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Employee name'),
    sa.Column('price', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False, comment='Price for exactly one measure of item'),
    sa.Column('total', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False, comment='Total price of items bought, should be equal to quantity times price'),
    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='Number of items bought'),
    sa.Column('measure', sa.SMALLINT(), autoincrement=False, nullable=False, comment='Type of measure for bought item'),
    sa.Column('nds', sa.SMALLINT(), autoincrement=False, nullable=False, comment='Type of VAT (НДС) for item'),
    sa.Column('payment', sa.SMALLINT(), autoincrement=False, nullable=False, comment='Item payment type'),
    sa.Column('product', sa.SMALLINT(), autoincrement=False, nullable=False, comment='Product category'),
    sa.ForeignKeyConstraint(['measure'], ['measures_orm.id'], name=op.f('fk_items_orm_measure_measures_orm'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['nds'], ['nds_orm.id'], name=op.f('fk_items_orm_nds_nds_orm'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment'], ['payments_orm.id'], name=op.f('fk_items_orm_payment_payments_orm'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product'], ['products_orm.id'], name=op.f('fk_items_orm_product_products_orm'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts_orm.id'], name=op.f('fk_items_orm_receipt_id_receipts_orm'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_items_orm'))
    )
    op.create_index(op.f('ix_items_orm_receipt_id'), 'items_orm', ['receipt_id'], unique=False)
    op.create_index(op.f('ix_items_orm_id'), 'items_orm', ['id'], unique=True)
    op.create_table('measures_orm',
    sa.Column('id', sa.SMALLINT(), server_default=sa.text("nextval('measures_orm_id_seq'::regclass)"), autoincrement=True, nullable=False, comment='Unique identifier of the measure'),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Full measure description'),
    sa.Column('pf_format', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Short code for print format of measure type'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_measures_orm'))
    )
    op.create_index(op.f('ix_measures_orm_id'), 'measures_orm', ['id'], unique=True)
    op.create_table('nds_orm',
    sa.Column('id', sa.SMALLINT(), server_default=sa.text("nextval('nds_orm_id_seq'::regclass)"), autoincrement=True, nullable=False, comment='Unique identifier of the VAT (НДС)'),
    sa.Column('rate_name', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Short tax rate name'),
    sa.Column('pf_format', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Short string code for print format of VAT type'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nds_orm'))
    )
    op.create_index(op.f('ix_nds_orm_id'), 'nds_orm', ['id'], unique=True)
    op.create_table('crpt_orm',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False, comment='Unique identifier for the receipt'),
    sa.Column('dump', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='Full receipt dump in JSON format from CRPT API'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crpt_orm'))
    )
    op.create_index(op.f('ix_crpt_orm_id'), 'crpt_orm', ['id'], unique=True)
    op.create_table('shops_orm',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False, comment='Unique identifier for the retailer'),
    sa.Column('retailer_id', sa.UUID(), autoincrement=False, nullable=False, comment='Link on retailer - owner of this shop'),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Physical address of a shop. Null if shop is online one'),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailers_orm.id'], name=op.f('fk_shops_orm_retailer_id_retailers_orm'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shops_orm')),
    sa.UniqueConstraint('retailer_id', 'address', name=op.f('uq_shops_orm_retailer_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_unique_online_shop_per_retailer'), 'shops_orm', ['retailer_id'], unique=True, postgresql_where='(address IS NULL)')
    op.create_index(op.f('ix_shops_orm_retailer_id'), 'shops_orm', ['retailer_id'], unique=True)
    op.create_index(op.f('ix_shops_orm_id'), 'shops_orm', ['id'], unique=True)
    op.create_table('payments_orm',
    sa.Column('id', sa.SMALLINT(), server_default=sa.text("nextval('payments_orm_id_seq'::regclass)"), autoincrement=True, nullable=False, comment='Unique identifier of the payment type'),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Payment type description'),
    sa.Column('pf_format', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Short string code for print format of payment type'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments_orm'))
    )
    op.create_index(op.f('ix_payments_orm_id'), 'payments_orm', ['id'], unique=True)
    op.create_table('receipts_orm',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False, comment='Unique identifier for the receipt'),
    sa.Column('t', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='Receipt timestamp'),
    sa.Column('s', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False, comment='Sum of prices by items in receipt'),
    sa.Column('fn', sa.BIGINT(), autoincrement=False, nullable=False, comment='Fiscal drive number (ФН)'),
    sa.Column('i', sa.BIGINT(), autoincrement=False, nullable=False, comment='Fiscal document number (ФД)'),
    sa.Column('fp', sa.BIGINT(), autoincrement=False, nullable=False, comment='Fiscal sign (ФП)'),
    sa.Column('n', sa.SMALLINT(), autoincrement=False, nullable=False, comment='Operation type'),
    sa.Column('crpt_id', sa.UUID(), autoincrement=False, nullable=False, comment='Reference to original CRPT data'),
    sa.ForeignKeyConstraint(['crpt_id'], ['crpt_orm.id'], name=op.f('fk_receipts_orm_crpt_id_crpt_orm'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('receipts_pkey')),
    sa.UniqueConstraint('t', 's', 'fn', 'i', 'fp', 'n', name=op.f('uq_receipts_orm_t'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_receipts_orm_id'), 'receipts_orm', ['id'], unique=True)
    op.create_index(op.f('ix_receipts_orm_crpt_id'), 'receipts_orm', ['crpt_id'], unique=True)
    # ### end Alembic commands ###
