"""Fill nds rates directory

Revision ID: 2ef20207e827
Revises: 9561895180cc
Create Date: 2026-08-23 11:45:50.805405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ef20207e827'
down_revision: Union[str, Sequence[str], None] = '9561895180cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    nds = sa.table(
        "nds_orm",
        sa.column("id", sa.Integer),
        sa.column("rate_name", sa.String),
        sa.column("pf_format", sa.String),
    )

    op.bulk_insert(
        nds,
        [
            {'id': 1, 'pf_format': 'НДС 20%', 'rate_name': 'Ставка НДС 20%'},
            {'id': 2, 'pf_format': 'НДС 10%', 'rate_name': 'Ставка НДС 10%'},
            {'id': 3, 'pf_format': 'НДС 20/120', 'rate_name': 'Ставка НДС расч. 20/120'},
            {'id': 4, 'pf_format': 'НДС 10/110', 'rate_name': 'Ставка НДС расч. 10/110'},
            {'id': 5, 'pf_format': 'НДС 0%', 'rate_name': 'Ставка НДС 0%'},
            {'id': 6, 'pf_format': '-', 'rate_name': 'НДС не облагается'},
            {'id': 7, 'pf_format': 'НДС 5%', 'rate_name': 'Ставка НДС 5%'},
            {'id': 8, 'pf_format': 'НДС 7%', 'rate_name': 'Ставка НДС 7%'},
            {'id': 9, 'pf_format': 'НДС 5/105', 'rate_name': 'Ставка НДС расч. 5/105'},
            {'id': 10, 'pf_format': 'НДС 7/107', 'rate_name': 'Ставка НДС расч. 7/107'},
            {'id': 11, 'pf_format': 'НДС 22%', 'rate_name': 'Ставка НДС 22%'},
            {'id': 12, 'pf_format': 'НДС 22/122', 'rate_name': 'Ставка НДС расч. 22/122'},
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("DELETE FROM nds_orm"))
    # ### end Alembic commands ###
