"""Product table 101 by OFD 1.2 (tag 1212)

Revision ID: 5d05c58ef444
Revises: 012728ff85b8
Create Date: 2026-08-26 00:29:46.554911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d05c58ef444'
down_revision: Union[str, Sequence[str], None] = '012728ff85b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    products = sa.table(
        "products_orm",
        sa.column("id", sa.Integer),
        sa.column("description", sa.String),
        sa.column("pf_format", sa.String),
    )

    op.bulk_insert(
        products,
        [
            {
                'id': 27,
                'pf_format': 'ВЫДАЧА ДЕНЕЖНЫХ СРЕДСТВ',
                'description': 'О выдаче денежных средств банковским платежным агентом'
            },
            {
                'id': 30,
                'pf_format': 'АТНМ',
                'description': 'О реализуемом подакцизном товаре, подлежащем маркировке средством идентификации, не имеющем кода маркировки'
            },
            {
                'id': 31,
                'pf_format': 'АТМ',
                'description': 'О реализуемом подакцизном товаре, подлежащем маркировке средством идентификации, имеющем код маркировки'
            },
            {
                'id': 32,
                'pf_format': 'ТНМ',
                'description': 'О реализуемом товаре, подлежащем маркировке средством идентификации, не имеющем кода маркировки, за исключением подакцизного товара'
            },
            {
                'id': 33,
                'pf_format': 'ТМ',
                'description': 'О реализуемом товаре, подлежащем маркировке средством идентификации, имеющем код маркировки, за исключением подакцизного товара'
            },
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        sa.text("DELETE FROM products_orm WHERE id IN (27, 30, 31, 32, 33)")
    )
    # ### end Alembic commands ###
