"""Receipt may be without operator employee

Revision ID: 508593a0dd80
Revises: 9145df5f7a18
Create Date: 2026-08-26 22:31:22.557979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '508593a0dd80'
down_revision: Union[str, Sequence[str], None] = '9145df5f7a18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('receipts_orm', 'employee_id',
               existing_type=sa.UUID(),
               nullable=True,
               existing_comment='Reference to employee, worked on this receipt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('receipts_orm', 'employee_id',
               existing_type=sa.UUID(),
               nullable=False,
               existing_comment='Reference to employee, worked on this receipt')
    # ### end Alembic commands ###
