"""Nds comments

Revision ID: 9fecaa586b20
Revises: 2ef20207e827
Create Date: 2026-08-23 12:04:15.438129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fecaa586b20'
down_revision: Union[str, Sequence[str], None] = '2ef20207e827'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nds_orm', 'id',
               existing_type=sa.SMALLINT(),
               comment='Unique identifier of the NDS (VAT)',
               existing_comment='Unique identifier of the VAT (НДС)',
               existing_nullable=False,
               existing_server_default=sa.text("nextval('nds_orm_id_seq'::regclass)"))
    op.alter_column('nds_orm', 'pf_format',
               existing_type=sa.VARCHAR(),
               comment='Short string code for print format of NDS (VAT) type',
               existing_comment='Short string code for print format of VAT type',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nds_orm', 'pf_format',
               existing_type=sa.VARCHAR(),
               comment='Short string code for print format of VAT type',
               existing_comment='Short string code for print format of NDS (VAT) type',
               existing_nullable=False)
    op.alter_column('nds_orm', 'id',
               existing_type=sa.SMALLINT(),
               comment='Unique identifier of the VAT (НДС)',
               existing_comment='Unique identifier of the NDS (VAT)',
               existing_nullable=False,
               existing_server_default=sa.text("nextval('nds_orm_id_seq'::regclass)"))
    # ### end Alembic commands ###
