"""Directory of product types

Revision ID: 0db7f65a44fc
Revises: 7c2a0cc25b0a
Create Date: 2026-08-22 23:23:02.535880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0db7f65a44fc'
down_revision: Union[str, Sequence[str], None] = '7c2a0cc25b0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products_orm',
    sa.Column('id', sa.SmallInteger(), nullable=False, comment='Unique identifier of the VAT (НДС)'),
    sa.Column('description', sa.String(), nullable=False, comment='VAT (НДС) description'),
    sa.Column('pf_format', sa.String(), nullable=False, comment='Short string code for print format of payment type'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products_orm'))
    )
    op.create_index(op.f('ix_products_orm_id'), 'products_orm', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_orm_id'), table_name='products_orm')
    op.drop_table('products_orm')
    # ### end Alembic commands ###
