"""Fill measure directory

Revision ID: 9561895180cc
Revises: cc305ff35f74
Create Date: 2026-08-23 10:57:31.875852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9561895180cc'
down_revision: Union[str, Sequence[str], None] = 'cc305ff35f74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    measures = sa.table(
        "measures_orm",
        sa.column("id", sa.Integer),
        sa.column("description", sa.String),
        sa.column("pf_format", sa.String),
    )

    op.bulk_insert(
        measures,
        [
            {'id': 0, 'pf_format': 'шт', 'description': 'Штука'},
            {'id': 10, 'pf_format': 'г', 'description': 'Грамм'},
            {'id': 11, 'pf_format': 'кг', 'description': 'Килограмм'},
            {'id': 12, 'pf_format': 'т', 'description': 'Тонна'},
            {'id': 20, 'pf_format': 'см', 'description': 'Сантиметр'},
            {'id': 21, 'pf_format': 'дм', 'description': 'Дециметр'},
            {'id': 22, 'pf_format': 'м', 'description': 'Метр'},
            {'id': 30, 'pf_format': 'кв. см', 'description': 'Квадратный сантиметр'},
            {'id': 31, 'pf_format': 'кв. дм', 'description': 'Квадратный дециметр'},
            {'id': 32, 'pf_format': 'кв. м', 'description': 'Квадратный метр'},
            {'id': 40, 'pf_format': 'мл', 'description': 'Миллилитр'},
            {'id': 41, 'pf_format': 'л', 'description': 'Литр'},
            {'id': 42, 'pf_format': 'куб. м', 'description': 'Кубический метр'},
            {'id': 50, 'pf_format': 'кВт*ч', 'description': 'Киловатт час'},
            {'id': 51, 'pf_format': 'Гкал', 'description': 'Гигакалория'},
            {'id': 70, 'pf_format': 'сутки', 'description': 'Сутки (день)'},
            {'id': 71, 'pf_format': 'час', 'description': 'Час'},
            {'id': 72, 'pf_format': 'мин', 'description': 'Минута'},
            {'id': 73, 'pf_format': 'с', 'description': 'Секунда'},
            {'id': 80, 'pf_format': 'Кбайт', 'description': 'Килобайт'},
            {'id': 81, 'pf_format': 'Мбайт', 'description': 'Мегабайт'},
            {'id': 82, 'pf_format': 'Гбайт', 'description': 'Гигабайт'},
            {'id': 83, 'pf_format': 'Тбайт', 'description': 'Терабайт'},
            {'id': 255, 'pf_format': '-', 'description': 'Другое'},
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("DELETE FROM measures_orm"))
    # ### end Alembic commands ###
