"""Directory of measure types

Revision ID: 7c2a0cc25b0a
Revises: 8c5d3b1715db
Create Date: 2026-08-22 23:22:23.052200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c2a0cc25b0a'
down_revision: Union[str, Sequence[str], None] = '8c5d3b1715db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measures_orm',
    sa.Column('id', sa.SmallInteger(), nullable=False, comment='Unique identifier of the measure'),
    sa.Column('description', sa.String(), nullable=False, comment='Full measure description'),
    sa.Column('pf_format', sa.String(), nullable=False, comment='Short code for print format of measure type'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_measures_orm'))
    )
    op.create_index(op.f('ix_measures_orm_id'), 'measures_orm', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_measures_orm_id'), table_name='measures_orm')
    op.drop_table('measures_orm')
    # ### end Alembic commands ###
