"""Shops only partial unique constraint

Revision ID: 9145df5f7a18
Revises: 5d05c58ef444
Create Date: 2026-08-26 22:25:56.090977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9145df5f7a18'
down_revision: Union[str, Sequence[str], None] = '5d05c58ef444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shops_orm_retailer_id'), table_name='shops_orm')
    op.create_index(op.f('ix_shops_orm_retailer_id'), 'shops_orm', ['retailer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shops_orm_retailer_id'), table_name='shops_orm')
    op.create_index(op.f('ix_shops_orm_retailer_id'), 'shops_orm', ['retailer_id'], unique=True)
    # ### end Alembic commands ###
