"""Fill payment types directory

Revision ID: 26fd3fd530c3
Revises: 9fecaa586b20
Create Date: 2026-08-23 12:05:10.603040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26fd3fd530c3'
down_revision: Union[str, Sequence[str], None] = '9fecaa586b20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    payment_types = sa.table(
        "payments_orm",
        sa.column("id", sa.Integer),
        sa.column("description", sa.String),
        sa.column("pf_format", sa.String),
    )

    op.bulk_insert(
        payment_types,
        [
            {'id': 1, 'pf_format': 'ПРЕДОПЛАТА 100%', 'description': 'Полная предварительная оплата до момента передачи предмета расчета'},
            {'id': 2, 'pf_format': 'ПРЕДОПЛАТА', 'description': 'Частичная предварительная оплата до момента передачи предмета расчета'},
            {'id': 3, 'pf_format': 'АВАНС', 'description': 'Аванс'},
            {'id': 4, 'pf_format': 'ПОЛНЫЙ РАСЧЕТ', 'description': 'Полная оплата, в том числе с учетом аванса (предварительной оплаты) в момент передачи предмета расчета'},
            {'id': 5, 'pf_format': 'ЧАСТИЧНЫЙ РАСЧЕТ И КРЕДИТ', 'description': 'Частичная оплата предмета расчета в момент его передачи с последующей оплатой в кредит'},
            {'id': 6, 'pf_format': 'ПЕРЕДАЧА В КРЕДИТ', 'description': 'Передача предмета расчета без его оплаты в момент его передачи с последующей оплатой в кредит'},
            {'id': 7, 'pf_format': 'ОПЛАТА КРЕДИТА', 'description': 'Оплата предмета расчета после его передачи с оплатой в кредит (оплата кредита)'},
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("DELETE FROM payments_orm"))
    # ### end Alembic commands ###
