"""Link receipt and employee

Revision ID: f1475407661c
Revises: 3a652e60909e
Create Date: 2026-08-25 22:07:22.614883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1475407661c'
down_revision: Union[str, Sequence[str], None] = '3a652e60909e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items_orm', 'name',
               existing_type=sa.VARCHAR(),
               comment='Item name',
               existing_comment='Employee name',
               existing_nullable=False)
    op.add_column('receipts_orm', sa.Column('employee_id', sa.UUID(), nullable=False, comment='Reference to employee, worked on this receipt'))
    op.create_index(op.f('ix_receipts_orm_employee_id'), 'receipts_orm', ['employee_id'], unique=False)
    op.create_foreign_key(op.f('fk_receipts_orm_employee_id_employees_orm'), 'receipts_orm', 'employees_orm', ['employee_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('retailers_orm', 'inn',
               existing_type=sa.VARCHAR(length=12),
               comment='INN (TIN) of a company or a single persona',
               existing_comment='TIN (ИНН) of a company or a single persona',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('retailers_orm', 'inn',
               existing_type=sa.VARCHAR(length=12),
               comment='TIN (ИНН) of a company or a single persona',
               existing_comment='INN (TIN) of a company or a single persona',
               existing_nullable=False)
    op.drop_constraint(op.f('fk_receipts_orm_employee_id_employees_orm'), 'receipts_orm', type_='foreignkey')
    op.drop_index(op.f('ix_receipts_orm_employee_id'), table_name='receipts_orm')
    op.drop_column('receipts_orm', 'employee_id')
    op.alter_column('items_orm', 'name',
               existing_type=sa.VARCHAR(),
               comment='Employee name',
               existing_comment='Item name',
               existing_nullable=False)
    # ### end Alembic commands ###
