"""Items table

Revision ID: 1e9f6510381b
Revises: 300d0d2529bb
Create Date: 2026-08-22 23:29:00.299506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e9f6510381b'
down_revision: Union[str, Sequence[str], None] = '300d0d2529bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items_orm',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the item'),
    sa.Column('receipt_id', sa.UUID(), nullable=False, comment='Relations to receipt with this item'),
    sa.Column('name', sa.String(), nullable=False, comment='Employee name'),
    sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=False, comment='Price for exactly one measure of item'),
    sa.Column('total', sa.Numeric(precision=15, scale=2), nullable=False, comment='Total price of items bought, should be equal to quantity times price'),
    sa.Column('quantity', sa.Float(), nullable=False, comment='Number of items bought'),
    sa.Column('measure', sa.SmallInteger(), nullable=False, comment='Type of measure for bought item'),
    sa.Column('nds', sa.SmallInteger(), nullable=False, comment='Type of VAT (НДС) for item'),
    sa.Column('payment', sa.SmallInteger(), nullable=False, comment='Item payment type'),
    sa.Column('product', sa.SmallInteger(), nullable=False, comment='Product category'),
    sa.ForeignKeyConstraint(['measure'], ['measures_orm.id'], name=op.f('fk_items_orm_measure_measures_orm'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['nds'], ['nds_orm.id'], name=op.f('fk_items_orm_nds_nds_orm'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment'], ['payments_orm.id'], name=op.f('fk_items_orm_payment_payments_orm'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product'], ['products_orm.id'], name=op.f('fk_items_orm_product_products_orm'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts_orm.id'], name=op.f('fk_items_orm_receipt_id_receipts_orm'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_items_orm'))
    )
    op.create_index(op.f('ix_items_orm_id'), 'items_orm', ['id'], unique=True)
    op.create_index(op.f('ix_items_orm_receipt_id'), 'items_orm', ['receipt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_orm_receipt_id'), table_name='items_orm')
    op.drop_index(op.f('ix_items_orm_id'), table_name='items_orm')
    op.drop_table('items_orm')
    # ### end Alembic commands ###
