"""
Directory of NDS rates

Revision ID: e2739bc6d098
Revises: ce6e8b6eac33
Create Date: 2026-08-22 23:18:01.314779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2739bc6d098'
down_revision: Union[str, Sequence[str], None] = 'ce6e8b6eac33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nds_orm',
    sa.Column('id', sa.SmallInteger(), nullable=False, comment='Unique identifier of the VAT (НДС)'),
    sa.Column('rate_name', sa.String(), nullable=False, comment='Short tax rate name'),
    sa.Column('pf_format', sa.String(), nullable=False, comment='Short string code for print format of VAT type'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nds_orm'))
    )
    op.create_index(op.f('ix_nds_orm_id'), 'nds_orm', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nds_orm_id'), table_name='nds_orm')
    op.drop_table('nds_orm')
    # ### end Alembic commands ###
