"""Shops table

Revision ID: 7589fc73aa00
Revises: cf29808f0a62
Create Date: 2026-08-22 23:26:36.060062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7589fc73aa00'
down_revision: Union[str, Sequence[str], None] = 'cf29808f0a62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shops_orm',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the retailer'),
    sa.Column('retailer_id', sa.UUID(), nullable=False, comment='Link on retailer - owner of this shop'),
    sa.Column('address', sa.String(), nullable=True, comment='Physical address of a shop. Null if shop is online one'),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailers_orm.id'], name=op.f('fk_shops_orm_retailer_id_retailers_orm'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shops_orm')),
    sa.UniqueConstraint('retailer_id', 'address', name=op.f('uq_shops_orm_retailer_id'))
    )
    op.create_index(op.f('ix_shops_orm_id'), 'shops_orm', ['id'], unique=True)
    op.create_index(op.f('ix_shops_orm_retailer_id'), 'shops_orm', ['retailer_id'], unique=True)
    op.create_index('ix_unique_online_shop_per_retailer', 'shops_orm', ['retailer_id'], unique=True, postgresql_where=sa.text('address IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_unique_online_shop_per_retailer', table_name='shops_orm', postgresql_where=sa.text('address IS NULL'))
    op.drop_index(op.f('ix_shops_orm_retailer_id'), table_name='shops_orm')
    op.drop_index(op.f('ix_shops_orm_id'), table_name='shops_orm')
    op.drop_table('shops_orm')
    # ### end Alembic commands ###
