"""Retailers table

Revision ID: cf29808f0a62
Revises: 0db7f65a44fc
Create Date: 2026-08-22 23:24:27.082718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf29808f0a62'
down_revision: Union[str, Sequence[str], None] = '0db7f65a44fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retailers_orm',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the retailer'),
    sa.Column('inn', sa.String(length=12), nullable=False, comment='TIN (ИНН) of a company or a single persona'),
    sa.Column('is_individual', sa.Boolean(), sa.Computed('length(inn) = 12', persisted=True), nullable=False, comment='Flag is the retailer is individual one, company otherwise'),
    sa.Column('name', sa.String(), nullable=False, comment='Name of a company or a persona'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retailers_orm'))
    )
    op.create_index(op.f('ix_retailers_orm_id'), 'retailers_orm', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retailers_orm_id'), table_name='retailers_orm')
    op.drop_table('retailers_orm')
    # ### end Alembic commands ###
