"""Cascade all

Revision ID: 012728ff85b8
Revises: f1475407661c
Create Date: 2026-08-25 23:52:26.135923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '012728ff85b8'
down_revision: Union[str, Sequence[str], None] = 'f1475407661c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_items_orm_receipt_id_receipts_orm'), 'items_orm', type_='foreignkey')
    op.drop_constraint(op.f('fk_items_orm_payment_payments_orm'), 'items_orm', type_='foreignkey')
    op.drop_constraint(op.f('fk_items_orm_measure_measures_orm'), 'items_orm', type_='foreignkey')
    op.drop_constraint(op.f('fk_items_orm_product_products_orm'), 'items_orm', type_='foreignkey')
    op.drop_constraint(op.f('fk_items_orm_nds_nds_orm'), 'items_orm', type_='foreignkey')
    op.create_foreign_key(op.f('fk_items_orm_product_products_orm'), 'items_orm', 'products_orm', ['product'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_items_orm_nds_nds_orm'), 'items_orm', 'nds_orm', ['nds'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_items_orm_payment_payments_orm'), 'items_orm', 'payments_orm', ['payment'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_items_orm_receipt_id_receipts_orm'), 'items_orm', 'receipts_orm', ['receipt_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_items_orm_measure_measures_orm'), 'items_orm', 'measures_orm', ['measure'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_receipts_orm_crpt_id_crpt_orm'), 'receipts_orm', type_='foreignkey')
    op.drop_constraint(op.f('fk_receipts_orm_employee_id_employees_orm'), 'receipts_orm', type_='foreignkey')
    op.drop_constraint(op.f('fk_receipts_orm_shop_id_shops_orm'), 'receipts_orm', type_='foreignkey')
    op.create_foreign_key(op.f('fk_receipts_orm_crpt_id_crpt_orm'), 'receipts_orm', 'crpt_orm', ['crpt_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_receipts_orm_employee_id_employees_orm'), 'receipts_orm', 'employees_orm', ['employee_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_receipts_orm_shop_id_shops_orm'), 'receipts_orm', 'shops_orm', ['shop_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_shops_orm_retailer_id_retailers_orm'), 'shops_orm', type_='foreignkey')
    op.create_foreign_key(op.f('fk_shops_orm_retailer_id_retailers_orm'), 'shops_orm', 'retailers_orm', ['retailer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_shops_orm_retailer_id_retailers_orm'), 'shops_orm', type_='foreignkey')
    op.create_foreign_key(op.f('fk_shops_orm_retailer_id_retailers_orm'), 'shops_orm', 'retailers_orm', ['retailer_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('fk_receipts_orm_shop_id_shops_orm'), 'receipts_orm', type_='foreignkey')
    op.drop_constraint(op.f('fk_receipts_orm_employee_id_employees_orm'), 'receipts_orm', type_='foreignkey')
    op.drop_constraint(op.f('fk_receipts_orm_crpt_id_crpt_orm'), 'receipts_orm', type_='foreignkey')
    op.create_foreign_key(op.f('fk_receipts_orm_shop_id_shops_orm'), 'receipts_orm', 'shops_orm', ['shop_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_receipts_orm_employee_id_employees_orm'), 'receipts_orm', 'employees_orm', ['employee_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_receipts_orm_crpt_id_crpt_orm'), 'receipts_orm', 'crpt_orm', ['crpt_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('fk_items_orm_measure_measures_orm'), 'items_orm', type_='foreignkey')
    op.drop_constraint(op.f('fk_items_orm_receipt_id_receipts_orm'), 'items_orm', type_='foreignkey')
    op.drop_constraint(op.f('fk_items_orm_payment_payments_orm'), 'items_orm', type_='foreignkey')
    op.drop_constraint(op.f('fk_items_orm_nds_nds_orm'), 'items_orm', type_='foreignkey')
    op.drop_constraint(op.f('fk_items_orm_product_products_orm'), 'items_orm', type_='foreignkey')
    op.create_foreign_key(op.f('fk_items_orm_nds_nds_orm'), 'items_orm', 'nds_orm', ['nds'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_items_orm_product_products_orm'), 'items_orm', 'products_orm', ['product'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_items_orm_measure_measures_orm'), 'items_orm', 'measures_orm', ['measure'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_items_orm_payment_payments_orm'), 'items_orm', 'payments_orm', ['payment'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_items_orm_receipt_id_receipts_orm'), 'items_orm', 'receipts_orm', ['receipt_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
