"""Employees table

Revision ID: 300d0d2529bb
Revises: 7589fc73aa00
Create Date: 2026-08-22 23:27:57.374029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '300d0d2529bb'
down_revision: Union[str, Sequence[str], None] = '7589fc73aa00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees_orm',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the employee'),
    sa.Column('shop_id', sa.UUID(), nullable=False, comment='Foreign key to shops table'),
    sa.Column('name', sa.String(), nullable=False, comment='Employee name'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops_orm.id'], name=op.f('fk_employees_orm_shop_id_shops_orm'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees_orm')),
    sa.UniqueConstraint('shop_id', 'name', name=op.f('uq_employees_orm_shop_id'))
    )
    op.create_index(op.f('ix_employees_orm_id'), 'employees_orm', ['id'], unique=True)
    op.create_index(op.f('ix_employees_orm_shop_id'), 'employees_orm', ['shop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_orm_shop_id'), table_name='employees_orm')
    op.drop_index(op.f('ix_employees_orm_id'), table_name='employees_orm')
    op.drop_table('employees_orm')
    # ### end Alembic commands ###
