"""Link shops and receipts

Revision ID: 875fc403b80e
Revises: 04e2a23f76c0
Create Date: 2026-08-23 00:01:40.844686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '875fc403b80e'
down_revision: Union[str, Sequence[str], None] = '04e2a23f76c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts_orm', sa.Column('shop_id', sa.UUID(), nullable=False, comment='Reference to shop, where receipt was made'))
    op.create_index(op.f('ix_receipts_orm_shop_id'), 'receipts_orm', ['shop_id'], unique=False)
    op.drop_constraint(op.f('fk_receipts_orm_crpt_id_crpt_orm'), 'receipts_orm', type_='foreignkey')
    op.create_foreign_key(op.f('fk_receipts_orm_crpt_id_crpt_orm'), 'receipts_orm', 'crpt_orm', ['crpt_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_receipts_orm_shop_id_shops_orm'), 'receipts_orm', 'shops_orm', ['shop_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_receipts_orm_shop_id_shops_orm'), 'receipts_orm', type_='foreignkey')
    op.drop_constraint(op.f('fk_receipts_orm_crpt_id_crpt_orm'), 'receipts_orm', type_='foreignkey')
    op.create_foreign_key(op.f('fk_receipts_orm_crpt_id_crpt_orm'), 'receipts_orm', 'crpt_orm', ['crpt_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_receipts_orm_shop_id'), table_name='receipts_orm')
    op.drop_column('receipts_orm', 'shop_id')
    # ### end Alembic commands ###
