"""Nullable item names

Revision ID: 6ef77428b339
Revises: 15834acb2e9b
Create Date: 2026-08-27 00:00:05.712231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ef77428b339'
down_revision: Union[str, Sequence[str], None] = '15834acb2e9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items_orm', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment='Item name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items_orm', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_comment='Item name')
    # ### end Alembic commands ###
