"""Directory of payment types

Revision ID: 8c5d3b1715db
Revises: e2739bc6d098
Create Date: 2026-08-22 23:20:59.153530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c5d3b1715db'
down_revision: Union[str, Sequence[str], None] = 'e2739bc6d098'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments_orm',
    sa.Column('id', sa.SmallInteger(), nullable=False, comment='Unique identifier of the payment type'),
    sa.Column('description', sa.String(), nullable=False, comment='Payment type description'),
    sa.Column('pf_format', sa.String(), nullable=False, comment='Short string code for print format of payment type'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments_orm'))
    )
    op.create_index(op.f('ix_payments_orm_id'), 'payments_orm', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_orm_id'), table_name='payments_orm')
    op.drop_table('payments_orm')
    # ### end Alembic commands ###
