"""
Split CRPT and receipts

Revision ID: ce6e8b6eac33
Revises: 08d523a284ef
Create Date: 2026-08-22 23:04:11.392679

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ce6e8b6eac33"
down_revision: Union[str, Sequence[str], None] = "08d523a284ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crpt_orm",
        sa.Column(
            "id", sa.UUID(), nullable=False, comment="Unique identifier for the receipt"
        ),
        sa.Column(
            "dump",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Full receipt dump in JSON format from CRPT API",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crpt_orm")),
    )
    op.create_index(op.f("ix_crpt_orm_id"), "crpt_orm", ["id"], unique=True)
    op.add_column(
        "receipts_orm",
        sa.Column(
            "crpt_id",
            sa.UUID(),
            nullable=False,
            comment="Reference to original CRPT data",
        ),
    )
    op.alter_column(
        "receipts_orm",
        "s",
        existing_type=sa.NUMERIC(precision=15, scale=2),
        comment="Sum of prices by items in receipt",
        existing_comment="Total amount",
        existing_nullable=False,
    )
    op.create_index(
        op.f("ix_receipts_orm_crpt_id"), "receipts_orm", ["crpt_id"], unique=True
    )
    op.create_foreign_key(
        op.f("fk_receipts_orm_crpt_id_crpt_orm"),
        "receipts_orm",
        "crpt_orm",
        ["crpt_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("receipts_orm", "crpt_data")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "receipts_orm",
        sa.Column(
            "crpt_data",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
            comment="Full receipt data in JSON format from CRPT API",
        ),
    )
    op.drop_constraint(
        op.f("fk_receipts_orm_crpt_id_crpt_orm"), "receipts_orm", type_="foreignkey"
    )
    op.drop_index(op.f("ix_receipts_orm_crpt_id"), table_name="receipts_orm")
    op.alter_column(
        "receipts_orm",
        "s",
        existing_type=sa.NUMERIC(precision=15, scale=2),
        comment="Total amount",
        existing_comment="Sum of prices by items in receipt",
        existing_nullable=False,
    )
    op.drop_column("receipts_orm", "crpt_id")
    op.drop_index(op.f("ix_crpt_orm_id"), table_name="crpt_orm")
    op.drop_table("crpt_orm")
    # ### end Alembic commands ###
