"""Drop employees

Revision ID: 110100f344e5
Revises: 471df3fb5bb3
Create Date: 2026-08-30 01:42:32.534335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '110100f344e5'
down_revision: Union[str, Sequence[str], None] = '471df3fb5bb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_orm_shop_id'), table_name='employees_orm')
    op.drop_constraint(op.f('uq_employees_orm_shop_id'), 'employees_orm', type_='unique')
    op.drop_constraint(op.f('fk_employees_orm_shop_id_shops_orm'), 'employees_orm', type_='foreignkey')
    op.drop_column('employees_orm', 'shop_id')
    op.drop_column('employees_orm', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees_orm', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Employee name'))
    op.add_column('employees_orm', sa.Column('shop_id', sa.UUID(), autoincrement=False, nullable=True, comment='Foreign key to shops table'))
    op.create_foreign_key(op.f('fk_employees_orm_shop_id_shops_orm'), 'employees_orm', 'shops_orm', ['shop_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_employees_orm_shop_id'), 'employees_orm', ['shop_id', 'name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_employees_orm_shop_id'), 'employees_orm', ['shop_id'], unique=False)
    # ### end Alembic commands ###
