"""Users

Revision ID: f45ca1c05f1b
Revises: dd259290b1ca
Create Date: 2026-09-04 21:53:34.045389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f45ca1c05f1b'
down_revision: Union[str, Sequence[str], None] = 'dd259290b1ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_orm',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier of a user'),
    sa.Column('username', sa.String(length=16), nullable=False, comment='Unique user name'),
    sa.Column('hashed_password', sa.String(length=60), nullable=False, comment='Hashed password from user account'),
    sa.Column('is_admin', sa.Boolean(), nullable=False, comment='Flag if user have additional privilegies'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users_orm'))
    )
    op.create_index(op.f('ix_users_orm_id'), 'users_orm', ['id'], unique=True)
    op.create_index(op.f('ix_users_orm_is_admin'), 'users_orm', ['is_admin'], unique=False)
    op.create_index(op.f('ix_users_orm_username'), 'users_orm', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_orm_username'), table_name='users_orm')
    op.drop_index(op.f('ix_users_orm_is_admin'), table_name='users_orm')
    op.drop_index(op.f('ix_users_orm_id'), table_name='users_orm')
    op.drop_table('users_orm')
    # ### end Alembic commands ###
