"""Retailer id on employees

Revision ID: dd259290b1ca
Revises: 110100f344e5
Create Date: 2026-08-30 01:43:13.013424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd259290b1ca'
down_revision: Union[str, Sequence[str], None] = '110100f344e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees_orm', sa.Column('retailer_id', sa.UUID(), nullable=False, comment='Foreign key to retailers table'))
    op.add_column('employees_orm', sa.Column('shop_id', sa.UUID(), nullable=True, comment='Foreign key to shops table'))
    op.add_column('employees_orm', sa.Column('name', sa.String(), nullable=False, comment='Employee name'))
    op.create_index(op.f('ix_employees_orm_retailer_id'), 'employees_orm', ['retailer_id'], unique=False)
    op.create_index(op.f('ix_employees_orm_shop_id'), 'employees_orm', ['shop_id'], unique=False)
    op.create_index('ix_employees_retailer_name_null_shop', 'employees_orm', ['retailer_id', 'name'], unique=True, postgresql_where=sa.text('shop_id IS NULL'))
    op.create_unique_constraint(op.f('uq_employees_orm_shop_id'), 'employees_orm', ['shop_id', 'name'])
    op.create_foreign_key(op.f('fk_employees_orm_shop_id_shops_orm'), 'employees_orm', 'shops_orm', ['shop_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_employees_orm_retailer_id_retailers_orm'), 'employees_orm', 'retailers_orm', ['retailer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_employees_orm_retailer_id_retailers_orm'), 'employees_orm', type_='foreignkey')
    op.drop_constraint(op.f('fk_employees_orm_shop_id_shops_orm'), 'employees_orm', type_='foreignkey')
    op.drop_constraint(op.f('uq_employees_orm_shop_id'), 'employees_orm', type_='unique')
    op.drop_index('ix_employees_retailer_name_null_shop', table_name='employees_orm', postgresql_where=sa.text('shop_id IS NULL'))
    op.drop_index(op.f('ix_employees_orm_shop_id'), table_name='employees_orm')
    op.drop_index(op.f('ix_employees_orm_retailer_id'), table_name='employees_orm')
    op.drop_column('employees_orm', 'name')
    op.drop_column('employees_orm', 'shop_id')
    op.drop_column('employees_orm', 'retailer_id')
    # ### end Alembic commands ###
