"""Link receipts with users

Revision ID: 353f38e9ff4c
Revises: f45ca1c05f1b
Create Date: 2026-09-05 17:49:20.137246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '353f38e9ff4c'
down_revision: Union[str, Sequence[str], None] = 'f45ca1c05f1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts_orm', sa.Column('owner_id', sa.UUID(), nullable=True, comment='Reference to a user that owns this receipt registry'))

    # Link existed receipts to a given default user UUID
    connection = op.get_bind()
    count = connection.execute(sa.text("SELECT COUNT(id) FROM receipts_orm")).scalar()
    if count > 0:
        owner_id = input("Enter default owner for existed receipts: ").strip()
        user_exists = connection.execute(sa.text("SELECT COUNT(id) FROM users_orm WHERE id = :owner_id"), {"owner_id": owner_id}).scalar()
        if not user_exists:
            raise ValueError("Not a valid UUID")
        connection.execute(sa.text("UPDATE receipts_orm SET owner_id = :owner_id WHERE owner_id IS NULL"), {"owner_id": owner_id})
    op.alter_column('receipts_orm', 'owner_id', nullable=False)

    op.create_index(op.f('ix_receipts_orm_owner_id'), 'receipts_orm', ['owner_id'], unique=False)
    op.create_foreign_key(op.f('fk_receipts_orm_owner_id_users_orm'), 'receipts_orm', 'users_orm', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_receipts_orm_owner_id_users_orm'), 'receipts_orm', type_='foreignkey')
    op.drop_index(op.f('ix_receipts_orm_owner_id'), table_name='receipts_orm')
    op.drop_column('receipts_orm', 'owner_id')
    # ### end Alembic commands ###
