"""Drop receipts

Revision ID: f67d180bf4d4
Revises: ef6f64a7471a
Create Date: 2026-08-29 22:46:10.108006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f67d180bf4d4'
down_revision: Union[str, Sequence[str], None] = 'ef6f64a7471a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_orm_id'), table_name='items_orm')
    op.drop_index(op.f('ix_items_orm_receipt_id'), table_name='items_orm')
    op.drop_table('items_orm')
    op.drop_index(op.f('ix_receipts_orm_crpt_id'), table_name='receipts_orm')
    op.drop_index(op.f('ix_receipts_orm_employee_id'), table_name='receipts_orm')
    op.drop_index(op.f('ix_receipts_orm_id'), table_name='receipts_orm')
    op.drop_index(op.f('ix_receipts_orm_retailer_id'), table_name='receipts_orm')
    op.drop_index(op.f('ix_receipts_orm_shop_id'), table_name='receipts_orm')
    op.drop_table('receipts_orm')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipts_orm',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False, comment='Unique identifier for the receipt'),
    sa.Column('crpt_id', sa.UUID(), autoincrement=False, nullable=False, comment='Reference to original CRPT data'),
    sa.Column('shop_id', sa.UUID(), autoincrement=False, nullable=True, comment='Reference to shop, where receipt was made'),
    sa.Column('t', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='Receipt timestamp'),
    sa.Column('s', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False, comment='Sum of prices by items in receipt'),
    sa.Column('fn', sa.BIGINT(), autoincrement=False, nullable=False, comment='Fiscal drive number (ФН)'),
    sa.Column('i', sa.BIGINT(), autoincrement=False, nullable=False, comment='Fiscal document number (ФД)'),
    sa.Column('fp', sa.BIGINT(), autoincrement=False, nullable=False, comment='Fiscal sign (ФП)'),
    sa.Column('n', sa.SMALLINT(), autoincrement=False, nullable=False, comment='Operation type'),
    sa.Column('employee_id', sa.UUID(), autoincrement=False, nullable=True, comment='Reference to employee, worked on this receipt'),
    sa.Column('retailer_id', sa.UUID(), autoincrement=False, nullable=False, comment='Reference to original CRPT data'),
    sa.ForeignKeyConstraint(['crpt_id'], ['crpt_orm.id'], name=op.f('fk_receipts_orm_crpt_id_crpt_orm'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees_orm.id'], name=op.f('fk_receipts_orm_employee_id_employees_orm'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailers_orm.id'], name=op.f('fk_receipts_orm_retailer_id_retailers_orm'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops_orm.id'], name=op.f('fk_receipts_orm_shop_id_shops_orm'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_receipts_orm')),
    sa.UniqueConstraint('t', 's', 'fn', 'i', 'fp', 'n', name=op.f('uq_receipts_orm_t'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_receipts_orm_shop_id'), 'receipts_orm', ['shop_id'], unique=False)
    op.create_index(op.f('ix_receipts_orm_retailer_id'), 'receipts_orm', ['retailer_id'], unique=False)
    op.create_index(op.f('ix_receipts_orm_id'), 'receipts_orm', ['id'], unique=True)
    op.create_index(op.f('ix_receipts_orm_employee_id'), 'receipts_orm', ['employee_id'], unique=False)
    op.create_index(op.f('ix_receipts_orm_crpt_id'), 'receipts_orm', ['crpt_id'], unique=True)
    op.create_table('items_orm',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False, comment='Unique identifier for the item'),
    sa.Column('receipt_id', sa.UUID(), autoincrement=False, nullable=False, comment='Relations to receipt with this item'),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Item name'),
    sa.Column('price', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False, comment='Price for exactly one measure of item'),
    sa.Column('total', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False, comment='Total price of items bought, should be equal to quantity times price'),
    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='Number of items bought'),
    sa.Column('measure', sa.SMALLINT(), autoincrement=False, nullable=False, comment='Type of measure for bought item'),
    sa.Column('nds', sa.SMALLINT(), autoincrement=False, nullable=False, comment='Type of VAT (НДС) for item'),
    sa.Column('payment', sa.SMALLINT(), autoincrement=False, nullable=False, comment='Item payment type'),
    sa.Column('product', sa.SMALLINT(), autoincrement=False, nullable=False, comment='Product category'),
    sa.ForeignKeyConstraint(['measure'], ['measures_orm.id'], name=op.f('fk_items_orm_measure_measures_orm'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['nds'], ['nds_orm.id'], name=op.f('fk_items_orm_nds_nds_orm'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment'], ['payments_orm.id'], name=op.f('fk_items_orm_payment_payments_orm'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product'], ['products_orm.id'], name=op.f('fk_items_orm_product_products_orm'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts_orm.id'], name=op.f('fk_items_orm_receipt_id_receipts_orm'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_items_orm'))
    )
    op.create_index(op.f('ix_items_orm_receipt_id'), 'items_orm', ['receipt_id'], unique=False)
    op.create_index(op.f('ix_items_orm_id'), 'items_orm', ['id'], unique=True)
    # ### end Alembic commands ###
