"""Non nullable retailers

Revision ID: ef6f64a7471a
Revises: d074b340ddcc
Create Date: 2026-08-29 20:46:48.036424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef6f64a7471a'
down_revision: Union[str, Sequence[str], None] = 'd074b340ddcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("""
        UPDATE receipts_orm r
        SET retailer_id = s.retailer_id
        FROM shops_orm s
        WHERE r.shop_id = s.id AND r.retailer_id IS NULL
    """))
    op.alter_column('receipts_orm', 'retailer_id',
               existing_type=sa.UUID(),
               nullable=False,
               existing_comment='Reference to original CRPT data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('receipts_orm', 'retailer_id',
               existing_type=sa.UUID(),
               nullable=True,
               existing_comment='Reference to original CRPT data')
    # ### end Alembic commands ###
