"""Non nullable shops

Revision ID: d074b340ddcc
Revises: 6ef77428b339
Create Date: 2026-08-29 20:14:34.000128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd074b340ddcc'
down_revision: Union[str, Sequence[str], None] = '6ef77428b339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees_orm', 'shop_id',
               existing_type=sa.UUID(),
               nullable=True,
               existing_comment='Foreign key to shops table')
    op.add_column('receipts_orm', sa.Column('retailer_id', sa.UUID(), nullable=False, comment='Reference to original CRPT data'))
    op.alter_column('receipts_orm', 'shop_id',
               existing_type=sa.UUID(),
               nullable=True,
               existing_comment='Reference to shop, where receipt was made')
    op.create_index(op.f('ix_receipts_orm_retailer_id'), 'receipts_orm', ['retailer_id'], unique=False)
    op.create_foreign_key(op.f('fk_receipts_orm_retailer_id_retailers_orm'), 'receipts_orm', 'retailers_orm', ['retailer_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_retailers_orm_inn'), 'retailers_orm', ['inn'])
    op.alter_column('shops_orm', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_comment='Physical address of a shop. Null if shop is online one')
    op.drop_index(op.f('ix_unique_online_shop_per_retailer'), table_name='shops_orm', postgresql_where='(address IS NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_unique_online_shop_per_retailer'), 'shops_orm', ['retailer_id'], unique=True, postgresql_where='(address IS NULL)')
    op.alter_column('shops_orm', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment='Physical address of a shop. Null if shop is online one')
    op.drop_constraint(op.f('uq_retailers_orm_inn'), 'retailers_orm', type_='unique')
    op.drop_constraint(op.f('fk_receipts_orm_retailer_id_retailers_orm'), 'receipts_orm', type_='foreignkey')
    op.drop_index(op.f('ix_receipts_orm_retailer_id'), table_name='receipts_orm')
    op.alter_column('receipts_orm', 'shop_id',
               existing_type=sa.UUID(),
               nullable=False,
               existing_comment='Reference to shop, where receipt was made')
    op.drop_column('receipts_orm', 'retailer_id')
    op.alter_column('employees_orm', 'shop_id',
               existing_type=sa.UUID(),
               nullable=False,
               existing_comment='Foreign key to shops table')
    # ### end Alembic commands ###
