"""Update indexes

Revision ID: d0ec47c86e3d
Revises: 351e1ed42d38
Create Date: 2026-09-14 00:01:38.340667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0ec47c86e3d'
down_revision: Union[str, Sequence[str], None] = '351e1ed42d38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crpt_orm_id'), table_name='crpt_orm')
    op.drop_index(op.f('ix_employees_orm_id'), table_name='employees_orm')
    op.drop_index(op.f('ix_items_orm_id'), table_name='items_orm')
    op.create_index(op.f('ix_items_orm_measure'), 'items_orm', ['measure'], unique=False)
    op.create_index(op.f('ix_items_orm_nds'), 'items_orm', ['nds'], unique=False)
    op.create_index(op.f('ix_items_orm_payment'), 'items_orm', ['payment'], unique=False)
    op.create_index(op.f('ix_items_orm_product'), 'items_orm', ['product'], unique=False)
    op.drop_constraint(op.f('fk_items_orm_nds_nds_orm'), 'items_orm', type_='foreignkey')
    op.drop_constraint(op.f('fk_items_orm_payment_payments_orm'), 'items_orm', type_='foreignkey')
    op.drop_constraint(op.f('fk_items_orm_measure_measures_orm'), 'items_orm', type_='foreignkey')
    op.drop_constraint(op.f('fk_items_orm_product_products_orm'), 'items_orm', type_='foreignkey')
    op.create_foreign_key(op.f('fk_items_orm_product_products_orm'), 'items_orm', 'products_orm', ['product'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_items_orm_payment_payments_orm'), 'items_orm', 'payments_orm', ['payment'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_items_orm_measure_measures_orm'), 'items_orm', 'measures_orm', ['measure'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_items_orm_nds_nds_orm'), 'items_orm', 'nds_orm', ['nds'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_measures_orm_id'), table_name='measures_orm')
    op.drop_index(op.f('ix_nds_orm_id'), table_name='nds_orm')
    op.drop_index(op.f('ix_payments_orm_id'), table_name='payments_orm')
    op.drop_index(op.f('ix_products_orm_id'), table_name='products_orm')
    op.drop_index(op.f('ix_receipts_orm_crpt_id'), table_name='receipts_orm')
    op.drop_index(op.f('ix_receipts_orm_id'), table_name='receipts_orm')
    op.create_unique_constraint(op.f('uq_receipts_orm_crpt_id'), 'receipts_orm', ['crpt_id'])
    op.drop_index(op.f('ix_retailers_orm_id'), table_name='retailers_orm')
    op.alter_column('shops_orm', 'address',
               existing_type=sa.VARCHAR(),
               comment='Physical address of a shop',
               existing_comment='Physical address of a shop. Null if shop is online one',
               existing_nullable=False)
    op.drop_index(op.f('ix_shops_orm_id'), table_name='shops_orm')
    op.drop_index(op.f('ix_users_orm_id'), table_name='users_orm')
    op.drop_index(op.f('ix_users_orm_is_admin'), table_name='users_orm')
    op.drop_index(op.f('ix_users_orm_username'), table_name='users_orm')
    op.create_unique_constraint(op.f('uq_users_orm_username'), 'users_orm', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_orm_username'), 'users_orm', type_='unique')
    op.create_index(op.f('ix_users_orm_username'), 'users_orm', ['username'], unique=True)
    op.create_index(op.f('ix_users_orm_is_admin'), 'users_orm', ['is_admin'], unique=False)
    op.create_index(op.f('ix_users_orm_id'), 'users_orm', ['id'], unique=True)
    op.create_index(op.f('ix_shops_orm_id'), 'shops_orm', ['id'], unique=True)
    op.alter_column('shops_orm', 'address',
               existing_type=sa.VARCHAR(),
               comment='Physical address of a shop. Null if shop is online one',
               existing_comment='Physical address of a shop',
               existing_nullable=False)
    op.create_index(op.f('ix_retailers_orm_id'), 'retailers_orm', ['id'], unique=True)
    op.drop_constraint(op.f('uq_receipts_orm_crpt_id'), 'receipts_orm', type_='unique')
    op.create_index(op.f('ix_receipts_orm_id'), 'receipts_orm', ['id'], unique=True)
    op.create_index(op.f('ix_receipts_orm_crpt_id'), 'receipts_orm', ['crpt_id'], unique=True)
    op.create_index(op.f('ix_products_orm_id'), 'products_orm', ['id'], unique=True)
    op.create_index(op.f('ix_payments_orm_id'), 'payments_orm', ['id'], unique=True)
    op.create_index(op.f('ix_nds_orm_id'), 'nds_orm', ['id'], unique=True)
    op.create_index(op.f('ix_measures_orm_id'), 'measures_orm', ['id'], unique=True)
    op.drop_constraint(op.f('fk_items_orm_nds_nds_orm'), 'items_orm', type_='foreignkey')
    op.drop_constraint(op.f('fk_items_orm_measure_measures_orm'), 'items_orm', type_='foreignkey')
    op.drop_constraint(op.f('fk_items_orm_payment_payments_orm'), 'items_orm', type_='foreignkey')
    op.drop_constraint(op.f('fk_items_orm_product_products_orm'), 'items_orm', type_='foreignkey')
    op.create_foreign_key(op.f('fk_items_orm_product_products_orm'), 'items_orm', 'products_orm', ['product'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_items_orm_measure_measures_orm'), 'items_orm', 'measures_orm', ['measure'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_items_orm_payment_payments_orm'), 'items_orm', 'payments_orm', ['payment'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_items_orm_nds_nds_orm'), 'items_orm', 'nds_orm', ['nds'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_items_orm_product'), table_name='items_orm')
    op.drop_index(op.f('ix_items_orm_payment'), table_name='items_orm')
    op.drop_index(op.f('ix_items_orm_nds'), table_name='items_orm')
    op.drop_index(op.f('ix_items_orm_measure'), table_name='items_orm')
    op.create_index(op.f('ix_items_orm_id'), 'items_orm', ['id'], unique=True)
    op.create_index(op.f('ix_employees_orm_id'), 'employees_orm', ['id'], unique=True)
    op.create_index(op.f('ix_crpt_orm_id'), 'crpt_orm', ['id'], unique=True)
    # ### end Alembic commands ###
