"""Operators missed translations

Revision ID: c678dad1cf28
Revises: 1790274000
Create Date: 2026-09-24 21:59:01.413240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c678dad1cf28'
down_revision: Union[str, Sequence[str], None] = '1790274000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('operators', 'id',
               existing_type=sa.UUID(),
               comment='Unique identifier for the operator',
               existing_comment='Unique identifier for the employee',
               existing_nullable=False)
    op.alter_column('operators', 'name',
               existing_type=sa.VARCHAR(),
               comment='Operator name',
               existing_comment='Employee name',
               existing_nullable=False)
    op.alter_column('receipts', 'operator_id',
               existing_type=sa.UUID(),
               comment='Reference to operator, worked on this receipt',
               existing_comment='Reference to employee, worked on this receipt',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('receipts', 'operator_id',
               existing_type=sa.UUID(),
               comment='Reference to employee, worked on this receipt',
               existing_comment='Reference to operator, worked on this receipt',
               existing_nullable=True)
    op.alter_column('operators', 'name',
               existing_type=sa.VARCHAR(),
               comment='Employee name',
               existing_comment='Operator name',
               existing_nullable=False)
    op.alter_column('operators', 'id',
               existing_type=sa.UUID(),
               comment='Unique identifier for the employee',
               existing_comment='Unique identifier for the operator',
               existing_nullable=False)
    # ### end Alembic commands ###
