"""Clean company name by INN

Revision ID: b2515debe849
Revises: c678dad1cf28
Create Date: 2026-10-08 23:26:11.379642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import httpx

from src.config import settings


# revision identifiers, used by Alembic.
revision: str = 'b2515debe849'
down_revision: Union[str, Sequence[str], None] = 'c678dad1cf28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

DADATA_URL = "https://suggestions.dadata.ru/suggestions/api/4_1/rs/findById/party"


def get_party_name(client: httpx.Client, inn: str) -> str:
    response = client.post(DADATA_URL, json={"query": inn})
    response.raise_for_status()

    suggestions = response.json().get("suggestions", [])
    if not suggestions:
        raise ValueError(f"No party found for INN {inn}")

    return suggestions[0]["value"]


def dadata_client() -> httpx.Client:
    return httpx.Client(
        timeout=10,
        headers={
            "content-type": "application/json",
            "accept": "application/json",
            "Authorization": f"Token {settings.dadata_token}",
            "X-Secret": settings.dadata_secret,
        },
    )


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    rows = conn.execute(sa.text("SELECT id, name, inn FROM retailers")).fetchall()

    with dadata_client() as client:
        for row in rows:
            try:
                name = get_party_name(client, row.inn)
            except Exception as e:
                raise RuntimeError(f"Could not fetch name for retailer {row.id}: {e}") from e

            conn.execute(
                sa.text(
                    "UPDATE retailers SET name = :name WHERE id = :id"
                ),
                {
                    "name": name,
                    "id": row.id
                },
            )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
