"""Tweak naming

Revision ID: 9e6f23bb36f2
Revises: b82225b4f0c9
Create Date: 2026-07-27 23:34:20.332064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e6f23bb36f2'
down_revision: Union[str, Sequence[str], None] = 'b82225b4f0c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('receipts', 'receipts_orm')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('receipts_orm', 'receipts')
    # ### end Alembic commands ###
